org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -DANDROID_NDK_HOME=H:\\Sdk\\ndk\\28.2.13676358 -DANDROID_NDK_ROOT=H:\\Sdk\\ndk\\28.2.13676358 -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2
android.useAndroidX=true
android.overridePathCheck=true
kotlin.compiler.execution.strategy=in-process
